### ISSUE TITLE
Brilliant work mate! 

### ISSUE THREAD

**Issue by raamsri** [twpayne/paragliding-articles#1]
This is fantastic stuff, cheers to the time and effort you have put into this Tom; and the selfless will to share your knowledge. 

Feel free to close the issue, I simply couldn't glide past without thanking you 😁

**Comment by raamsri** [comment]
@twpayne

**Comment by twpayne** [comment]
Thank you so much for your kind words @raamsri! Much appreciated, and very happy to hear that this is helpful to you.
